# permissions for end users to edit markdowncontents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: markdowncontent-editor-role
rules:
- apiGroups:
  - webstatic.caiofralmeida.github.io
  resources:
  - markdowncontents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webstatic.caiofralmeida.github.io
  resources:
  - markdowncontents/status
  verbs:
  - get
